# Generated by Django 6.0.7 on 2026-07-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_name', models.CharField(max_length=100, verbose_name='建筑名称')),
                ('building_code', models.CharField(blank=True, max_length=50, verbose_name='建筑编号')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='建筑描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '建筑',
                'verbose_name_plural': '建筑',
                'db_table': 'Building',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Floor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('floor_name', models.CharField(max_length=50, verbose_name='楼层名称')),
                ('floor_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='楼层面积(m²)')),
                ('floor_height', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='层高(m)')),
                ('floor_plan_file', models.CharField(blank=True, max_length=500, verbose_name='底图PDF路径')),
                ('floor_plan_data', models.JSONField(blank=True, default=dict, verbose_name='平面图数据')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='floors', to='projects.building', verbose_name='所属建筑')),
            ],
            options={
                'verbose_name': '楼层',
                'verbose_name_plural': '楼层',
                'db_table': 'Floor',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200, verbose_name='项目名称')),
                ('project_code', models.CharField(blank=True, max_length=50, verbose_name='项目编号')),
                ('location', models.CharField(blank=True, max_length=200, verbose_name='详细地址')),
                ('description', models.TextField(blank=True, verbose_name='项目描述')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='projects', to='common.cityconfig', verbose_name='所属城市')),
            ],
            options={
                'verbose_name': '项目',
                'verbose_name_plural': '项目',
                'db_table': 'Project',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ExtraLoad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('PCW', 'PCW'), ('配电室空调', '配电室空调'), ('工艺热水', '工艺热水'), ('消防池保温', '消防池保温'), ('消防池护层', '消防池护层'), ('其他', '其他')], max_length=50, verbose_name='负荷类别')),
                ('load_value', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='负荷值(kW)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('building', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='extra_loads', to='projects.building', verbose_name='所属建筑（空=项目级）')),
                ('water_temp_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.watertempconfig', verbose_name='关联冷冻水分类')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='extra_loads', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '额外负荷',
                'verbose_name_plural': '额外负荷',
                'db_table': 'ExtraLoad',
            },
        ),
        migrations.AddField(
            model_name='building',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buildings', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('room_name', models.CharField(max_length=100, verbose_name='功能区域名称')),
                ('room_code', models.CharField(blank=True, max_length=50, verbose_name='功能区域编号')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='面积(m²)')),
                ('height', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='吊顶高度(m)')),
                ('volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='体积(m³)')),
                ('design_temp_requirement', models.CharField(blank=True, max_length=50, verbose_name='设计温度要求')),
                ('design_humidity_requirement', models.CharField(blank=True, max_length=50, verbose_name='设计相对湿度要求')),
                ('temp_precision', models.CharField(blank=True, choices=[('±1', '±1'), ('±2', '±2'), ('±3', '±3'), ('±5', '±5'), ('none', '无要求')], max_length=10, verbose_name='温控精度')),
                ('indoor_calc_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='室内计算温度(℃)')),
                ('indoor_calc_humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='室内计算相对湿度(%)')),
                ('cleanliness_level', models.CharField(blank=True, max_length=50, verbose_name='洁净度等级')),
                ('civil_load_index', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='土建指标(W/m²)')),
                ('lighting_load_index', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='照明指标(W/m²)')),
                ('personnel_load_index', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='人员指标(W/人)')),
                ('personnel_count', models.IntegerField(blank=True, null=True, verbose_name='人数')),
                ('electric_equipment_power', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='电动设备功率(kW)')),
                ('electric_equipment_coefficient', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='电动设备系数')),
                ('heated_equipment_power_with_exhaust', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='有排风电热功率(kW)')),
                ('heated_equipment_coefficient_with_exhaust', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='有排风电热系数')),
                ('heated_equipment_power_without_exhaust', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='无排风电热功率(kW)')),
                ('heated_equipment_coefficient_without_exhaust', models.DecimalField(blank=True, decimal_places=4, max_digits=5, null=True, verbose_name='无排风电热系数')),
                ('heat_exhaust_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='热排风量(m³/h)')),
                ('acid_exhaust_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='酸性排风量(m³/h)')),
                ('alkali_exhaust_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='碱性排风量(m³/h)')),
                ('organic_exhaust_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='有机排风量(m³/h)')),
                ('dust_exhaust_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='含尘排风量(m³/h)')),
                ('total_exhaust_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='总排风量(m³/h)')),
                ('pressure_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='功能区域压差(Pa)')),
                ('air_change_rate', models.IntegerField(blank=True, null=True, verbose_name='设计换气次数(次/h)')),
                ('supply_air_temp_diff', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='送风温差(℃)')),
                ('fresh_air_water_mode', models.CharField(blank=True, choices=[('single', '单水温模式'), ('dual', '两阶段模式')], default='single', max_length=10, verbose_name='新风冷冻水模式')),
                ('status', models.CharField(choices=[('draft', '草稿'), ('active', '已确认')], default='active', max_length=10, verbose_name='状态')),
                ('description', models.CharField(blank=True, max_length=500, verbose_name='描述')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('floor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rooms', to='projects.floor', verbose_name='所属楼层')),
                ('fresh_air_water_temp_config', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.watertempconfig', verbose_name='单水温档/第一段档')),
                ('fresh_air_water_temp_config_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='common.watertempconfig', verbose_name='两阶段第二段档')),
                ('terminal_water_temp_config', models.ForeignKey(blank=True, help_text='末端负荷归属的冷冻水档，空=中温默认（ADR-0001）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='terminal_rooms', to='common.watertempconfig', verbose_name='末端冷冻水档')),
            ],
            options={
                'verbose_name': '功能区域',
                'verbose_name_plural': '功能区域',
                'db_table': 'Room',
                'ordering': ['sort_order', 'id'],
            },
        ),
    ]
