# Generated by Django 6.0.7 on 2026-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CityConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city_name', models.CharField(max_length=50, verbose_name='城市名称')),
                ('province', models.CharField(blank=True, max_length=50, verbose_name='省份')),
                ('station_name', models.CharField(blank=True, max_length=100, verbose_name='台站名称')),
                ('station_code', models.CharField(blank=True, max_length=20, verbose_name='台站编号')),
                ('latitude', models.CharField(blank=True, max_length=20, verbose_name='纬度')),
                ('longitude', models.CharField(blank=True, max_length=20, verbose_name='经度')),
                ('altitude', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='海拔(m)')),
                ('statistical_years', models.CharField(blank=True, max_length=50, verbose_name='统计年份')),
                ('pressure_winter', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='冬季大气压力(hPa)')),
                ('pressure_summer', models.DecimalField(blank=True, decimal_places=1, max_digits=8, null=True, verbose_name='夏季大气压力(hPa)')),
                ('wind_speed_winter', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='冬季风速(m/s)')),
                ('wind_speed_summer', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='夏季风速(m/s)')),
                ('temp_dry_ac_summer', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='夏季空调干球温度(℃)')),
                ('temp_wet_ac_summer', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='夏季空调湿球温度(℃)')),
                ('temp_dry_ac_winter', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='冬季空调干球温度(℃)')),
                ('humidity_ac_winter', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True, verbose_name='冬季空调相对湿度(%)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '城市配置',
                'verbose_name_plural': '城市配置',
                'db_table': 'CityConfig',
                'ordering': ['province', 'city_name'],
            },
        ),
        migrations.CreateModel(
            name='WaterTempConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_type_name', models.CharField(max_length=50, verbose_name='配置名称')),
                ('supply_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='供水温度(℃)')),
                ('return_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='回水温度(℃)')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '冷冻水温度配置',
                'verbose_name_plural': '冷冻水温度配置',
                'db_table': 'WaterTempConfig',
            },
        ),
    ]
