# Generated by Django 6.0.7 on 2026-07-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='watertempconfig',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='water_temp_configs', to='projects.project', verbose_name='所属项目'),
        ),
        migrations.AlterUniqueTogether(
            name='watertempconfig',
            unique_together={('project', 'temp_type_name')},
        ),
    ]
