# Generated by Django 6.0.7 on 2026-07-15 00:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='观测时刻')),
                ('dry_bulb_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='干球温度(℃)')),
                ('wet_bulb_temp', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='湿球温度(℃)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='相对湿度(%)')),
                ('atmospheric_pressure', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='大气压(hPa)')),
                ('wind_speed', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, verbose_name='风速(m/s)')),
                ('solar_radiation', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='太阳辐射(W/m²)')),
                ('source', models.CharField(default='api', max_length=10, verbose_name='数据来源')),
                ('imputed_flag', models.BooleanField(default=False, verbose_name='是否插补')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('city', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_records', to='common.cityconfig', verbose_name='城市')),
            ],
            options={
                'verbose_name': '气象数据',
                'verbose_name_plural': '气象数据',
                'db_table': 'WeatherRecord',
                'ordering': ['timestamp'],
                'unique_together': {('city', 'timestamp')},
            },
        ),
    ]
