# Generated by Django 6.0.7 on 2026-07-14 16:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimulationRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('batch_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='批次ID')),
                ('mode', models.CharField(choices=[('weather_driven', '气象驱动'), ('ratio_coefficient', '比例系数法')], default='weather_driven', max_length=20, verbose_name='仿真模式')),
                ('status', models.CharField(choices=[('PENDING', '等待'), ('STARTED', '进行中'), ('SUCCESS', '成功'), ('FAILURE', '失败')], default='SUCCESS', max_length=10, verbose_name='状态')),
                ('result_summary', models.JSONField(blank=True, default=dict, verbose_name='结果摘要')),
                ('error_message', models.TextField(blank=True, verbose_name='错误信息')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='simulation_runs', to='projects.room', verbose_name='功能区域')),
            ],
            options={
                'verbose_name': '仿真任务',
                'verbose_name_plural': '仿真任务',
                'db_table': 'SimulationRun',
                'ordering': ['-created_at'],
            },
        ),
    ]
