# Generated by Django 6.0.7 on 2026-07-14 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LoadSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope', models.CharField(choices=[('floor', '楼层'), ('building', '建筑'), ('project', '项目')], max_length=20, verbose_name='汇总层级')),
                ('category', models.CharField(max_length=50, verbose_name='负荷类别')),
                ('fresh_air_load', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='新风冷负荷(kW)')),
                ('terminal_load', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='末端负荷(kW)')),
                ('extra_load', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='额外负荷(kW)')),
                ('total_load', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='负荷合计(kW)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '负荷汇总',
                'verbose_name_plural': '负荷汇总',
                'db_table': 'LoadSummary',
            },
        ),
        migrations.CreateModel(
            name='RoomCalcResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('civil_load', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='土建负荷(kW)')),
                ('lighting_load', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='照明负荷(kW)')),
                ('personnel_load', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='人员负荷(kW)')),
                ('electric_equipment_load', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='电动设备负荷(kW)')),
                ('heated_equipment_load', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='电热设备负荷(kW)')),
                ('terminal_load', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='末端负荷合计(kW)')),
                ('total_exhaust_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='总排风量(m³/h)')),
                ('infiltration_air_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='压差渗透风量(m³/h)')),
                ('fresh_air_volume', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='新风量(m³/h)')),
                ('indoor_enthalpy_calc', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='室内焓值(kJ/kg)')),
                ('outdoor_enthalpy_calc', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='室外焓值(kJ/kg)')),
                ('enthalpy_diff', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='焓差(kJ/kg)')),
                ('cold_load_index', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='冷指标(W/m²)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '功能区域计算结果',
                'verbose_name_plural': '功能区域计算结果',
                'db_table': 'RoomCalcResult',
            },
        ),
        migrations.CreateModel(
            name='RoomLoadByWaterTemp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('terminal_load', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='末端负荷(kW)')),
                ('fresh_air_load', models.DecimalField(decimal_places=4, default=0, max_digits=10, verbose_name='新风冷负荷(kW)')),
                ('total_load', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='总负荷(kW)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
            ],
            options={
                'verbose_name': '按水温分类负荷',
                'verbose_name_plural': '按水温分类负荷',
                'db_table': 'RoomLoadByWaterTemp',
            },
        ),
    ]
