# Generated by Django 6.0.7 on 2026-07-14 15:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('calculation', '0001_initial'),
        ('common', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loadsummary',
            name='building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.building', verbose_name='建筑（空=项目级）'),
        ),
        migrations.AddField(
            model_name='loadsummary',
            name='floor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.floor', verbose_name='楼层（空=建筑/项目级）'),
        ),
        migrations.AddField(
            model_name='loadsummary',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='项目'),
        ),
        migrations.AddField(
            model_name='loadsummary',
            name='water_temp_config',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='common.watertempconfig', verbose_name='水温档（空=汇总所有水温）'),
        ),
        migrations.AddField(
            model_name='roomcalcresult',
            name='room',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='calc_result', to='projects.room', verbose_name='功能区域'),
        ),
        migrations.AddField(
            model_name='roomloadbywatertemp',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loads_by_water_temp', to='projects.room', verbose_name='功能区域'),
        ),
        migrations.AddField(
            model_name='roomloadbywatertemp',
            name='water_temp_config',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='room_loads', to='common.watertempconfig', verbose_name='冷冻水温度档'),
        ),
        migrations.AlterUniqueTogether(
            name='roomloadbywatertemp',
            unique_together={('room', 'water_temp_config')},
        ),
    ]
