# Generated by Django 6.0.7 on 2026-07-14 15:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ForecastScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='场景名称')),
                ('start_date', models.DateField(verbose_name='开始日期')),
                ('weather_source', models.CharField(choices=[('api', 'API 自动'), ('manual', '手动上传')], default='api', max_length=10, verbose_name='天气来源')),
                ('status', models.CharField(choices=[('active', '活跃'), ('paused', '暂停'), ('archived', '归档')], default='active', max_length=10, verbose_name='状态')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_scenarios', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '预测场景',
                'verbose_name_plural': '预测场景',
                'db_table': 'ForecastScenario',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ForecastProductionRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_value', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='负荷率(%)')),
                ('duration_hours', models.IntegerField(verbose_name='持续时长(小时)')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='production_rates', to='forecast.forecastscenario', verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '生产负荷率',
                'verbose_name_plural': '生产负荷率',
                'db_table': 'ForecastProductionRate',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='ForecastHourlyResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='时刻')),
                ('outdoor_temp', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='室外温度(℃)')),
                ('ratio_coefficient', models.DecimalField(decimal_places=4, max_digits=8, verbose_name='比例系数 K')),
                ('predicted_load', models.DecimalField(decimal_places=4, max_digits=12, verbose_name='预测负荷(kW)')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='计算批次时间')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forecast_results', to='projects.room', verbose_name='功能区域')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_results', to='forecast.forecastscenario', verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '预测逐时结果',
                'verbose_name_plural': '预测逐时结果',
                'db_table': 'ForecastHourlyResult',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='ForecastWeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(verbose_name='时刻')),
                ('temp_dry', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='干球温度(℃)')),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='相对湿度(%)')),
                ('source', models.CharField(default='api', max_length=10, verbose_name='来源')),
                ('fetched_at', models.DateTimeField(auto_now_add=True, verbose_name='抓取时间')),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weather_data', to='forecast.forecastscenario', verbose_name='所属场景')),
            ],
            options={
                'verbose_name': '预测天气',
                'verbose_name_plural': '预测天气',
                'db_table': 'ForecastWeatherData',
                'ordering': ['timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RatioCoefficient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_min', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度区间下限(℃)')),
                ('temp_max', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='温度区间上限(℃)')),
                ('rate_percent', models.IntegerField(verbose_name='负荷率(%)')),
                ('coefficient', models.DecimalField(decimal_places=4, max_digits=6, verbose_name='系数 K')),
                ('is_default', models.BooleanField(default=True, verbose_name='是否系统默认')),
                ('project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ratio_coefficients', to='projects.project', verbose_name='项目级覆盖')),
            ],
            options={
                'verbose_name': '比例系数',
                'verbose_name_plural': '比例系数',
                'db_table': 'RatioCoefficient',
                'unique_together': {('temp_min', 'temp_max', 'rate_percent', 'project')},
            },
        ),
    ]
