# Generated by Django 6.0.7 on 2026-07-14 15:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConversationSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_stage', models.CharField(choices=[('s1_project', '①项目基本信息'), ('s2_water_temp', '②冷冻水温度配置'), ('s3_building', '③建筑结构信息'), ('s4_room', '④功能区域参数'), ('s5_extra_load', '⑤额外负荷信息'), ('s6_summary', '⑥汇总预览与确认')], default='s1_project', max_length=20, verbose_name='当前阶段')),
                ('stage_status', models.JSONField(blank=True, default=dict, verbose_name='各阶段完成状态')),
                ('draft_payload', models.JSONField(blank=True, default=dict, verbose_name='对话草稿暂存')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conversation_sessions', to='projects.project', verbose_name='所属项目')),
            ],
            options={
                'verbose_name': '对话采集会话',
                'verbose_name_plural': '对话采集会话',
                'db_table': 'ConversationSession',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ConversationMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('system', '系统'), ('user', '用户'), ('assistant', '助手')], max_length=10, verbose_name='角色')),
                ('content', models.TextField(verbose_name='消息内容')),
                ('extracted_payload', models.JSONField(blank=True, default=dict, verbose_name='抽取结果')),
                ('stage', models.CharField(choices=[('s1_project', '①项目基本信息'), ('s2_water_temp', '②冷冻水温度配置'), ('s3_building', '③建筑结构信息'), ('s4_room', '④功能区域参数'), ('s5_extra_load', '⑤额外负荷信息'), ('s6_summary', '⑥汇总预览与确认')], max_length=20, verbose_name='所属阶段')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='时间戳')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='conversation.conversationsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '对话消息',
                'verbose_name_plural': '对话消息',
                'db_table': 'ConversationMessage',
                'ordering': ['timestamp'],
            },
        ),
    ]
